# Site settings
title: 小白小白
description: 小白小白
favicon: /assets/img/avatar.JPG
baseurl:
url: https://www.hutianxiang.com.cn
rss_url:

# Build settings

timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
